### ISSUE TITLE
Simpler modified utf-7 implementation

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#117]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

Look at Mathieu's alternative way of doing this which uses Python's built-in UTF-7 codec and then applies fixups.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/120

**Comment by NicolasLM** [comment]
I believe https://github.com/mjs/imapclient/commit/480127ffb74b384484fca8f2161b1cdd3281447c closes this issue.
