### ISSUE TITLE
Move almost all docs to Sphinx

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#119]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

Integrate README and HACKING content into Sphinx docs and make them stubs which refer to the real docs. This means there's only one place people need to look and less for me to maintain.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/122

**Comment by freddrake** [comment]
Isn't this substantially done?  There are only a few things left in the README.

**Comment by NicolasLM** [comment]
Right, closing. Thanks!
