### ISSUE TITLE
Use a larger maximum line length

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#139]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

imaplib enforces a maximum inbound line length of 10,000. Dovecot defaults to a maximum line length of 65536 making it easy for an otherwise valid search of a large mailbox to result in an error.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/142

**Comment by NicolasLM** [comment]
@mjs Now that imaplib raised `_MAXLINE` I believe we can close this issue.
