### ISSUE TITLE
Use more precise exception classes

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#141]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

For example, instead of IMAPClient raising an exception like:

```
imaplib.error: select failed: "Mailbox doesn't exist: days"
```

It would be better if a specific "mailbox doesn't exist" error was used. The same applies to other kinds of errors.

Requested by Thomas Güttler.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/144

**Comment by NicolasLM** [comment]
Closing as it is related to #267
