### ISSUE TITLE
certfi support

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#164]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

Ensure it easy to use certfi with IMAPClient

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/166

**Comment by mjs** [comment]
Perhaps becomes irrelevant once we're no longer using backports.ssl?

**Comment by NicolasLM** [comment]
Not really related to backports.ssl as far as I know. It's either we let Python get the list of trusted CA from the OS with the risk of them being outdated, or we get an updated list of trusted CA via certifi.

We have to be careful though, as mail servers are notoriously slow to comply with SSL best practices.

**Comment by NicolasLM** [comment]
After digging a bit, with the `ssl` module it looks like certs from `certifi` can be used this way:

```python
import ssl
import certifi

ssl_context = ssl.create_default_context(cafile=certifi.where())
```
