### ISSUE TITLE
Sort out PEP 470 compliance

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#179]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

(see email) 

Remove links to IMAPClient files hosted elsewhere.

http://legacy.python.org/dev/peps/pep-0470/

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/182

**Comment by NicolasLM** [comment]
I believe this issue can be closed.

**Comment by mjs** [comment]
Yes,  I believe this is fine now.
