### ISSUE TITLE
bypassing ssl verification could be easier

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#185]
Originally reported by: **Harry P (Bitbucket: [hjwp](https://bitbucket.org/hjwp))**

---

Hi-ho!

We use a self-signed cert on the imap server for our CI loop.  We upgraded to the latest imapclient and found it more restrictive on ssl certs.

We started with a workaround based on the provided `create_default_context` function:

```
#!python
ssl_context = imapclient.create_default_context()
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE
server = imapclient.IMAPClient(IMAP_HOST, ssl=True, ssl_context=ssl_context)
```

And that worked on most machines, but on some windows machines (on Azure), I guess some sort of weirdness with the default CA certs caused an ugly failure:

```
  File "c:\buildshare\buildbot-slave\rudolf-googlechrome\build\tests\browser\fts\imap.py", line 47, in connect
    ssl_context = imapclient.create_default_context()
  File "C:\Python27\lib\site-packages\imapclient\tls.py", line 109, in create_default_context
    context.load_verify_locations(cadata=certs)
  File "C:\Python27\lib\site-packages\backports\ssl\core.py", line 647, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "C:\Python27\lib\site-packages\OpenSSL\SSL.py", line 528, in load_verify_locations
    _raise_current_error()
  File "C:\Python27\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: []
```

So instead we built our own fresh context using the `ssl` packaged directly:

```
#!python
ssl_context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE
server = imapclient.IMAPClient(IMAP_HOST, ssl=True, ssl_context=ssl_context)
```

And that seems to work everywhere.

So, not sure if bug or just recommended workaround for anyone else out there suffering from this problem.

But maybe it could turn into a feature suggestion?  Could there be a higher-level, simpler API for initiating an IMAP client with "ignore ssl cert problems"?  Something like a `verify_ssl=False` argument in the constructor?

Just a thought.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/188

**Comment by NicolasLM** [comment]
I believe this issue can be closed: there is nothing we can do if `ssl.create_default_context()` does not work.

We could add a section about SSL in the `Advanced usage` of the documentation explaining how to turn off certificate checking though.

**Comment by NicolasLM** [comment]
Closing as we now provide documentation and examples to turn off SSL verification, see http://imapclient.readthedocs.io/en/master/concepts.html#tls-ssl
