### ISSUE TITLE
Investigate claims that UTF-7 encoding/decoding doesn't always work

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#187]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

See:  https://github.com/MarechJ/py3_imap_utf7

If/when any problems are fixed, ask the author to update the page. Also add comments to SO where this is mentioned.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/190

**Comment by mlorant** [comment]
So should we take a peek at [this module of MailPile](https://github.com/mailpile/Mailpile/blob/master/mailpile/mail_source/imap_utf7.py) then? Or anything built-in appeared since then (not likely I guess)?

It should have the 1.1.0 milestone too I think (instead of soon) since it's more a bug than a new feature...

**Comment by NicolasLM** [comment]
I don't know much about UTF-7 and how it is used in IMAP but:

```python
>>> s = 'foo\r\n\nbar\n'
>>> s == s.encode('utf-7').decode('utf-7')
True
```

Isn't this enough?

**Comment by mlorant** [comment]
When reading the RFC 2152, I thought there was specificity needed by IMAP servers but in fact, the [utf7 codec of CPython seems to be compliant with this same RFC](https://github.com/python/cpython/blob/5075416b8fedc5526b643dabc915f7945fa0d969/Lib/test/test_unicode.py#L1581).

I haven't dig into `imap_utf7` code before, but I'm wondering why there is a difference imapclient result and the built-in one:
```
In [15]: 'A≠α'.encode('utf-7')
Out[15]: b'A+ImADsQ-'

In [16]: imap_utf7.encode('A≠α')
Out[16]: b'A&ImADsQ-'
```
The shift character is defined as "+" is the RFC, but twisted code (we forked in imapclient) is using "&"... Anyway, it is not as simple as that I guess.

```
# With imap_utf7.encode = s.encode('utf-7') and imap_utf7.decode = s.decode('utf-7')
In [4]: conn.list_folders()
Out[4]: 
[((b'\\HasChildren',), b'.', 'INBOX'),
 ((b'\\HasNoChildren',), b'.', 'INBOX.INBOX.Envoy&AOk-s'),
 ((b'\\HasNoChildren',), b'.', 'INBOX.A&ImADsQ-'),

# Set autoreload and revert to original code 
In [7]: %load_ext autoreload
In [8]: %autoreload 2
In [9]: conn = IMAPClient('...')
In [10]: conn.login('...')
Out[10]: b'[CAPABILITY IMAP4rev1 ...] Logged in'

In [11]: conn.list_folders()
Out[11]: 
[((b'\\HasChildren',), b'.', 'INBOX'),
 ((b'\\HasNoChildren',), b'.', 'INBOX.INBOX.Envoyés'),
 ((b'\\HasNoChildren',), b'.', 'INBOX.A≠α'),
```

**Comment by NicolasLM** [comment]
You're right, IMAP uses a modified version of the utf-7 encoding: https://tools.ietf.org/html/rfc3501#section-5.1.3
