### ISSUE TITLE
Expand installation docs

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#194]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

List Linux and OS X (and Windows?) packages that are required in order for dependencies to work.

cryptography needs: 

```
# Ubuntu:
sudo apt-get install build-essential libssl-dev libffi-dev python-dev

# Fedora/RH
sudo yum install gcc libffi-devel python-devel openssl-devel
```

pyOpenSSL: is now pure Python so is probably fine.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/197

**Comment by NicolasLM** [comment]
Once done, #217 will makes this way easier.

**Comment by mjs** [comment]
Agreed. I'm going to close this has this becomes irrelevant once 2.0 is out.
