### ISSUE TITLE
Bypass backports.ssl if possible

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#196]
Originally reported by: **Arnold Bechtoldt (Bitbucket: [bechtoldt](https://bitbucket.org/bechtoldt))**

---

I'm using imapclient on python 3.x (https://github.com/bechtoldt/tabellarius) and it would be great to skip/bypass backports.ssl since it has a smaller audience/community than pyopenssl, which is important from a security-specific view.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/199

**Comment by mjs** [comment]
#225 does exactly this.

**Comment by bechtoldt** [comment]
thx, will give it a try soon!
