### ISSUE TITLE
Segfault 11 on Mac (10.10.5)  with Python 3.4.4 for outlook.com's IMAP

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#198]
Originally reported by: **Paul Hammant (Bitbucket: [paul_hammant](https://bitbucket.org/paul_hammant))**

---

$ python3 testtt.py 
Traceback (most recent call last):
  File "testtt.py", line 18, in <module>
    print('%d messages in INBOX' % select_info['EXISTS'])
KeyError: 'EXISTS'
Segmentation fault: 11
1. I've done DiskUtility - disk repair (sometimes people ask you to do that for segfault-y bug reports)
2. I uninstalled Python3.5.1 from homebrew, and did the downloadable Python 3.4.4 installer from Python.org.
3. Using it's pip3 command, I installed imapclient today.
4. I took your first script from the https://imapclient.readthedocs.org site, and changed imap server, user, password (and turned on SSL).
5. Running you script causes the seg-fault, as above.  The Apple app-crash-catcher opens up. I've dismissed it. This is consistently reproducible for me, so I can run it again, and send debug information.

I can reproduce this on two Macs. One a MacBookAir (2011), one a MacBookPro (2014). Both running Yosemite 10.10.5.  I was trying first with Python 3.5.1, but I note that is not listed as supported, so I downgraded and tried again.

I would test the same script on Windows10/Python334 but I get SSL errors. See below.

Note - I was logging issues with backport.ssl too - https://github.com/alekstorm/backports.ssl/issues/16 and https://github.com/alekstorm/backports.ssl/issues/15 and https://github.com/alekstorm/backports.ssl/issues/14 

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/201

**Comment by NicolasLM** [comment]
Probably related to an incompatibility between MacOS/Python/backports.ssl. I believe this issue can be closed.

**Comment by mjs** [comment]
IMAPClient 2.x will no longer use backports.ssl etc. This problem will go away when that happens.
