### ISSUE TITLE
Set up CI infrastructure

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#216]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/219

**Comment by bechtoldt** [comment]
in case you need inspiration, check https://github.com/bechtoldt/tabellarius ;)

**Comment by mjs** [comment]
Also check out Circle and Snap

**Comment by mjs** [comment]
Done!
