### ISSUE TITLE
Revert to using Python's built-in SSL/TLS support

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#217]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

---

Using backports.ssl, cryptography.io and pyOpenSSL for TLS support is proving to be more trouble than it's worth. Python's TLS support has been greatly improved since Python 2.7.9 and 3.4 and most people have access to these versions these days.

On older platforms fake it as best as possible, like urllib3 does:
https://github.com/kennethreitz/requests/blob/05d90b9379f57ee5f5d0beb268c495793fb5b2d7/requests/packages/urllib3/util/ssl_.py

Consider emitting warnings when on older versions.

---
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/220

**Comment by pilona** [comment]
Would this be a sufficient quick fix in the meantime?

    --- old.py	2016-09-27 12:54:33.256795485 -0400
    +++ tls.py	2016-09-27 12:56:21.319793550 -0400
    @@ -36,7 +36,11 @@
         check_pyopenssl_version()
     
     try:
    -    from backports import ssl
    +    if (version_info.major == 3 and tuple(version_info) < (3, 4) or
    +        version_info.major == 2 and tuple(version_info) < (2,7,9)):
    +        from backports import ssl
    +    else:
    +        import ssl
     except ImportError:
         raise ImportError("backports.ssl is not installed")
     
This would certainly unbreak TLS SNI support!

**Comment by mjs** [comment]
#225 does most of the hard work to make this happen, using backports.ssl for older Python versions and the built-in ssl module for 2.7.9+ and 3.4+.

I'm still wondering about dropping backports.ssl, pyOpenSSL etc completely and just warning the user when they're on a Python version with crappy ssl support though.

**Comment by boehlke** [comment]
New versions of imaplib provide a starttls command which works fine for me. Why not just use it if available (see my PR)

**Comment by NicolasLM** [comment]
I would encourage you to drop `backports.ssl` altogether. A few reasons:

* It is unmaintained, which is a big red flag for a library that is about security
* It is installed by default with the wheel of `imapclient`, even on Python 3.6.1
* It makes debugging SSL issues very hard (backports.ssl vs PyOpenSSL vs  SSL in the standard library)
* The industry largely adopted Python 3.5 which has a working SSL implementation by default. Supporting older versions is not as important as it used to be.
* It comes with its own bugs. For instance its use of `select` makes it impossible to have a process dealing with more than 1024 IDLE connections at the same time.

**Comment by mjs** [comment]
Yeah, I'm convinced. IMAPClient 2.x will no longer depend on `backports.ssl`and just use the built-in `ssl` package as best as possible.

**Comment by mlorant** [comment]
So it seems there's a consensus...

![Kill it with fire](http://www.gifbin.com/bin/25yuswsw28295.gif)

**Comment by mjs** [comment]
Ha ha :+1:

**Comment by NicolasLM** [comment]
Closing, see #299 and #310
