### ISSUE TITLE
Integrate Nylas' patches back in

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#219]
Originally reported by: **Menno Smits (Bitbucket: [mjs0](https://bitbucket.org/mjs0))**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/mjs0/imapclient/issue/222

**Comment by bengotow** [comment]
Thanks for publishing this to GitHub! I'm happy to help get this stuff back in. We'd also like to avoid people finding our GitHub repo instead of this one. To move toward that, I'm going to create a new `nylas/imapclient` as a fork of this repo, rebase our commits there, and send you a PR.

**Comment by mjs** [comment]
Done in PR #220. Thanks @bengotow!
