### ISSUE TITLE
IMAPClient should poll if IDLE is not supported by the server

### ISSUE THREAD

**Issue by DevKiHyun** [mjs/imapclient#238]
When I use Idle() method, then an error occurs.

imaplib.error: Unexpected IDLE reasponse: b'JKDI3 BAD Error in IMAP command IDLE: Unknown command.'

How can I solve this error?

This is my code

 `from imapclient import IMAPClient`
 `from backports import ssl`
 `context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)`
 `server = IMAPClient('imap.host.com', use_uid = True, ssl = True, ssl_context = context)`
 `server.login(user_id, user_password)`
 `server.select_folder('INBOX')`
 `server.idle()`

**Comment by DevKiHyun** [comment]
When I use gmail host, then work is well. But if I use 'naver' host, that error occurs. So I think the cause of that error is the problem of the specific site. I will try some tests later, and tell result to you.

**Comment by DevKiHyun** [comment]
When I put print (resp) in the idle () function and use the naver mail account, an error other than None is displayed in resp. 
resp is 
b'OOIJ3 BAD Error in IMAP command IDLE: Unknown command'

what is it mean?

Obviously, if I use gmail, resp prints None.

**Comment by mjs** [comment]
[IDLE](https://tools.ietf.org/html/rfc2177) is an IMAP extension so it's not required that servers support it. You can check what the server supports using the `capabilities` method like this:

```python
# (after login)
print server.capabilities()
```

Or more specifically:

```python
print server.has_capability("IDLE")
```

Can you check the capabilities of the "naver" server?

**Comment by DevKiHyun** [comment]
Yeah, I do server.capabilitoes(), then it show me this
(b'IMAP4REV1', b'LITERAL+', b'SASL-IR', b'ID', b'UNSELECT', b'CHILDREN', b'UIDPLUS', b'LIST-EXTENDED', b'I18NLEVEL=1', b'WITHIN', b'MOVE', b'QUOTA', b'SPECIAL-USE')

Is this mean that 'naver' server isn't support "IDLE"?
I think so.

**Comment by DevKiHyun** [comment]
There is one more question.
I make code like this
`while 1:`
`     responses = server.idle_chek(timeout = 600)`
`     print(responses)`

then, the first few times printed [ ] every 10 minutes.
But as time goes on, it printed [ ] continuously in a very short time period.

It is not understandable to output the result in a period of almost 3 seconds from a certain point of time since the result should be output unconditionally every 10 minutes.
Is there anything I overlooked about idle_check ()?

**Comment by DevKiHyun** [comment]
oh, Imap idle timeout recommended within 30 minutes!
I resolved by restarting idle mode every 30 minutes.
And if it is a server that does not support idle commands, I think I should do Polling. If you have other ways, please recommend to me.

**Comment by mjs** [comment]
The client can only poll if IDLE is not available.

I guess that IMAPClient could transparently fall back to polling in this case. Do you think this is a good idea?

**Comment by DevKiHyun** [comment]
Yeah, I think so too. Polling is the best way in this case.

**Comment by mjs** [comment]
I've changed the ticket title to reflect this feature

**Comment by DevKiHyun** [comment]
If do polling, do I implement it in such a way that first get a list in advance and then list it after a certain time (specified by the user) and compare the differences?

**Comment by mjs** [comment]
Comparing changes in the set of message UIDs should work. You can take advantage of the fact that UIDs only increase. This means that if you want to see new messages you can just query for messages with UIDs greater than the last UID seen (but please make sure you understand UIDVALIDITY).

If the server supports the CONDSTORE extensions, you should consider using them. This will let you efficiently detect changes to messages. See https://tools.ietf.org/html/rfc4551

**Comment by NicolasLM** [comment]
> I guess that IMAPClient could transparently fall back to polling in this case. Do you think this is a good idea?

I would rather have another method using either IDLE or poll to track the arrival of new messages to avoid the confusion of the `idle()` method not using the IMAP `IDLE` command.

**Comment by NicolasLM** [comment]
Moving the discussion to #296.
