### ISSUE TITLE
Is Fetch slow?

### ISSUE THREAD

**Issue by DevKiHyun** [mjs/imapclient#239]
If  I "fetch" a particular email, it will take 0.05 seconds on average.
As a result of the test, fetching 10 messages takes about 1 second. I think 10 mail to 1 second belongs to the slower side than I thought. I think this is a time-consuming one because 'fetch' tries to fetch the entire contents of the mail. For this reason, it seems to take a long time.
If I want to get only the 'date', 'subject', and 'from' of the mail, I can use fetch([index], ('BODY.[HEADER]')). It takes 3 seconde per 100 mail.  But I don't know that this is fast.

What's a good way to fetch a lot of mail fastly?

**Comment by mjs** [comment]
The speed of fetch will be greatly influenced by the quality of the server implementation, server hardware and the network between the client and server. There's not much that IMAPClient can do to help.

Are you coming fetch with just one message id at a time? If so, I would recommend trying to fetch chunks of message IDs together. You will probably did that reducing the number of round trips to the server will improve performance.

Also experiment with the fields you are requesting (e.g. SU JECT,  INTERNALDATE etc). Selecting exactly the data you are interested in is usually a good idea but some servers may be slow at retrieving certain kinds of fields.

**Comment by mjs** [comment]
Sorry for all the typos above. I'm typing from a phone in a taxi 😁
