### ISSUE TITLE
Do I must select a folder before 'idle ()'?

### ISSUE THREAD

**Issue by DevKiHyun** [mjs/imapclient#241]
If new changes occur in any folder, I want to know the folder and its elements. 
However, I must select only one folder before using 'idle'. 
Is there any way to detect changes in any folder without selecting a specific folder?

**Comment by mjs** [comment]
This is just the way IMAP works. Each connection can only monitor the currently selected folder. If you want to monitor multiple mailboxes at once you'll need to use multiple connections (and servers may limit the number of concurrent connections for an account).
