### ISSUE TITLE
`_convert_to_ENVELOPE` (and subcall to `util.to_unicode`) only support ascii data

### ISSUE THREAD

**Issue by mlorant** [mjs/imapclient#243]
When using `fetch(uids, ['ENVELOPE'])`, we get a `imapclient.response_types.Envelope` namedtuple. However, this object may result in subcomponent that call `imapclient.util.to_unicode`. However this methods, decode bytes data only with the ascii codec.

For some reasons, some senders does not encode the data before sending the e-mail, resulting in object like this...

```In [5]: addr = Address(b'Ren\xe9', None, 'rene', 'domain.com')
In [6]: str(addr)
---------------------------------------------------------------------------
/dir/to/imapclient/response_types.py in __str__(self)
     56     def __str__(self):
     57         return formataddr((
---> 58             to_unicode(self.name),
     59             to_unicode(self.mailbox) + '@' + to_unicode(self.host)))
     60 

/dir/to/imapclient/util.py in to_unicode(s)
     10 def to_unicode(s):
     11     if isinstance(s, binary_type):
---> 12         return s.decode('ascii')
     13     return s
     14 

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 3: ordinal not in range(128)
```

I think `imapclient` should handle this and either raise a proper custom exception which informs the developer why the data is incorrect or decode the data (using latin1 codec in this case), if possible...

**Comment by mlorant** [comment]
I don't know what to do about it in fact. This happened to me once or twice over millions of e-mails scanned (and I can't reproduce it now. I should have noted accounts & msgid concerned *sighs*)... 

The exception occurred only if you actually used the `__str__` and not while parsing the ENVELOPE. I guess this can be ignored since it is often poorly encoded, not useful, e-mails... I don't think raising IMAPClientException nor creating a new exception class for that would be more useful.

**Comment by mjs** [comment]
I can't think of a good solution either... given that it's just for `__str__()` and only occurs rarely maybe it would be ok to use the "ignore" or "replace" error policies when decoding here? The caller can always use the attributes directly to retrieve the original values.

**Comment by mlorant** [comment]
FYI: Not possible to use "replace", since imaplib raises the same problem after in subsequennt `formataddr` call.
