### ISSUE TITLE
Consider using the standard Python logging facility

### ISSUE THREAD

**Issue by NicolasLM** [mjs/imapclient#250]
Currently imapclient implements a custom logging through the `debug` attribute.

This works but does not give the user much freedom. It could be improved by using the [standard logging module](https://docs.python.org/3/library/logging.html), which is quite straightforward.

The main advantage as a library is that you only have to log things, leaving everything else (destination, levels, formatting...) to the final user of the library.

@mjs I can submit the patch if you are interested in this approach.

**Comment by mjs** [comment]
This sounds great but there's one complication. Most (all?) of the debugging output actually comes from imaplib, which IMAPClient wraps. In order for this to work it looks like you'd have to patch the `_mesg` method of the imap.IMAP4 instance, to intercept the messages.

I'm happy to see a patch which does this though.

I'm planning that IMAPClient 3.x will do way with relying on imaplib BTW.

**Comment by NicolasLM** [comment]
Done in #252.

It currently uses two loggers: one for IMAPClient itself (`imapclient.imapclient`) and one more verbose for imaplib (`imapclient.imaplib`).

It gives the ability to the final user to silence imaplib for instance.

**Comment by NicolasLM** [comment]
Closing as #252 is merged.
