### ISSUE TITLE
Small problems with example.py in Python 3.6 

### ISSUE THREAD

**Issue by phoebebright** [mjs/imapclient#253]
I'm not sure if this should be noted separately for later versions of Python 3 or the example changed, but to get https://github.com/mjs/imapclient/blob/master/imapclient/examples/example.py to work I had to make two changes::

      18    print('%d messages in INBOX' % select_info['EXISTS'])

becomes::

      18     print('%d messages in INBOX' % select_info[b'EXISTS'])

and::

     26 for msgid, data in response.iteritems():

becomes::

     26 for msgid, data in response.items():

**Comment by mjs** [comment]
Thanks! I'll get this fixed.

**Comment by mlorant** [comment]
I was also surprised by this when I migrated from Py2 to Py3. Perhaps this points a possible improvement:  responses dict keys are always plain ASCII string AFAIK. Should the imapclient parser _automagically_ encodes bytes into str?

The client code would be easier to read, less error-prone (who never forgot a `b''` when manipulating the response dict?). Of course, it would need some deprecation plans and supports both styles (but be careful to not double the memory usage though...) OR take advantage of the 2.0.0 version release to make it backward incompatible (changes in client code should not be that hard to do anyway).
