### ISSUE TITLE
Run live tests automatically with various test accounts under TravisCI

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#259]
This requires a little bit of thought to prevent the test account details leaking. Travis seems to provide some functionality to help with this.

**Comment by mjs** [comment]
Need to ensure that we're only hitting a particular account once when testing across Python versions. Either need to limit build concurrency to 1 (might be too slow but is worth trying initially) or install Python versions manually and use tox (doesn't seem too hard).

I'm also thinking a separate imapclient-livetest repo to keep the livetest running infrastructure separate from the main repo.

**Comment by NicolasLM** [comment]
I believe these tests are often called integration tests, it might be a more common wording than live tests.

I don't think that keeping these tests in the main repository is a problem. It may even be easier for external contributors: having to make a PR to a single repo is better than asking for two different PRs. Of course if for a technical reason with CI it's easier to have two separate repos, let's pick the easy way.

There is also the possibility to run these tests on a single version of Python. After all unit tests are here of catching most of the problems, and the less fine-grained integration tests exist to make sure the code actually behaves well with real servers.

**Comment by mlorant** [comment]
I would keep them in the main repo too. But maybe they should be moved in a dedicated test folder instead of being next to the main code, like the unit tests.

**Comment by mjs** [comment]
To be clear, I intend to keep the tests themselves in the main repo. I agree that this is important.

The other repo would just have the config files for the test accounts we are testing and any scripts to help run the tests under TravisCI. It would check out an IMAPClient branch and run the tests in that branch for the accounts we want to test against.

**Comment by mjs** [comment]
Not happening.
