### ISSUE TITLE
Move tests out of the imapclient package

### ISSUE THREAD

**Issue by NicolasLM** [mjs/imapclient#266]
Most projects have their tests out of the main package, in a separate `test` package. See for instance requests, flask and celery.

This prevents tests from being included in the distribution (even if there are other ways to achieve this) and is more consistent with the practices of the Python ecosystem.

**Comment by mjs** [comment]
I'm happy for this to happen. Some time ago I had the idea that the unit tests should be able to be run from any IMAPClient installation (using something like `python -m imapclient.tests`) but it's pretty clear that lots of other people don't want that :)
