### ISSUE TITLE
Make SSL connections the default

### ISSUE THREAD

**Issue by NicolasLM** [mjs/imapclient#273]
In 2017 there is little reasons to connect to a mailbox over plain text.

As this is a breaking change I propose to do it for 2.0.0.

**Comment by mlorant** [comment]
Just to be clear: this is just switch `ssl=False` to `ssl=True` in the `IMAPClient.__init__` arguments list?

It is indeed quite insane to do "real" stuff today regarding e-mail exchanges without SSL today, so promoting this way its usage seems nice at first glance. Plus, it does not change the way you are using the library after the connection... 

We should just ensure the error message is clear if someone is trying for the first time to connect to a non-SSL port. Also make it clear in the documentation that SSL can be disabled.

**Comment by NicolasLM** [comment]
Yes, this is what I had in mind.

**Comment by mjs** [comment]
I'm mostly +1 on this. The only time where not connecting with SSL is ok is when you're going to use starttls but I suspect this is a sufficiently rare case.

As @mlorant says, we need to ensure the docs are clear on this.
