### ISSUE TITLE
Fill in new documentation sections

### ISSUE THREAD

**Issue by mjs** [mjs/imapclient#275]
A number of documentation TODOs were introduced in #269 and need to to be completed.

**Comment by mlorant** [comment]
For info, there are 2 sections to fill in:

- advanced.rst / Handling large mailboxes (issue #255)
- quickstart.rst / Connect to a server and send our first commands

**Comment by NicolasLM** [comment]
I have mixed feelings with the quickstart since the example given in `index.rst` is already a good quickstart.

**Comment by NicolasLM** [comment]
That being said, a very quick example should be the first thing in the README.
