### ISSUE TITLE
Separate connect timeout from read/write timeout

### ISSUE THREAD

**Issue by NicolasLM** [mjs/imapclient#285]
Most of the times:
- connecting to a server is a very fast operation (the heavy work is done by the kernel so a slow application does not impact connection much)
- once connected, slow servers can take minutes to execute an IMAP command (extreme example: reading an old email from tape storage)

Thus it makes sense to have a low timeout for connecting and a longer one for read/write operations.

See for instance: http://urllib3.readthedocs.io/en/latest/user-guide.html#using-timeouts

**Comment by mlorant** [comment]
For reference, see ML topic _[Timeout when trying to append a big/long message into a mailbox](https://groups.io/g/imapclient/topic/6016437)_ (main subject not related but the idea pop there)

**Comment by NicolasLM** [comment]
Closed by #289
