### ISSUE TITLE
please release IMAPclient 1.x which have mock in test dependencies only.

### ISSUE THREAD

**Issue by fizyk** [mjs/imapclient#286]
It would allow me to bump my project to the new mock library. Especially seeing that on 1.x branch it's been committed over a month ago. (not to mention, that it installs mock on production where it's not needed)

**Comment by NicolasLM** [comment]
The `1.1.0` milestone only contains low-priority issues. @mjs What do you think?

**Comment by mjs** [comment]
It's already been fixed in the 1.x branch. We just need to get 1.1.0 out the door. This can be done once #243 is fixed.
