### ISSUE TITLE
Move TestableIMAPClient into imapclient module so it is shipped to users

### ISSUE THREAD

**Issue by mlorant** [mjs/imapclient#295]
Using the 1.0.2 release, I am using `TestableIMAPClient` to mock calls the IMAP connection and test our own code against the most closest IMAPClient instance possible, while TestableIMAPClient mock all network interaction internally. 

With the current master branch (specifcally the commit 9e411a5), `tests/testable_imapclient` is not shipped anymore. I would like to see this one re-included in the `imapclient` module. Even though it is not documentated AFAIK, it allows some users, who likes take a peek in the internals like me, to write  unit tests with one less mock  :)

**Comment by NicolasLM** [comment]
That makes sense, I don't have any problem with moving it back the the `imapclient` package as long as the feature is clearly documented (mostly to prevent anyone from moving it out again).

**Comment by mlorant** [comment]
Regarding issue #286: we need `mock` in this module... But we can remove `mock` from the dependencies and raises a pretty `ImportError` when the user is trying to import `testable_imapclient` if we can't find `unittest.mock` nor `mock`.
The user will then be invited to install it only if the user really wants to use this utility class, which is not mandatory, and (s)he has Python < 3.3.

**Comment by mlorant** [comment]
Merged, closing.
