### ISSUE TITLE
Issue with imap_utf7.decode() and imap_utf7.encode()

### ISSUE THREAD

**Issue by anaswy** [mjs/imapclient#304]
For a encoded mailbox name having special character tab ('\t'), the tab character gets lost if we decode and re-encode the mailbox name.
Sample code:
```
from imapclient import imap_utf7
mailbox = "MailboxWithTab&AAk-Here"
decoded_mailbox = imap_utf7.decode(mailbox)
encoded_mailbox = imap_utf7.encode(decoded_mailbox)
print mailbox
print encoded_mailbox
```

After running the above code, following will be the output:
```
MailboxWithTab&AAk-Here
MailboxWithTab&-Here
```

You will notice that encoded string **AAk** is getting lost
Python version: 2.7.10
imapclient version: 1.0.2

**Comment by mlorant** [comment]
This has been resolved in #300 but not yet released:

```
>>> import imapclient
>>> imapclient.__version__
'2.0.0-alpha'
>>> mailbox = "MailboxWithTab\tHere"
>>> imapclient.imap_utf7.encode(mailbox)
b'MailboxWithTab&AAk-Here'
>>> imapclient.imap_utf7.decode(imapclient.imap_utf7.encode(mailbox))
'MailboxWithTab\tHere'
```

**Comment by anaswy** [comment]
Thanks for the fixing it even before I reported.
Can you please tell approximate timeline of when I can expect the fix to get released.

**Comment by mlorant** [comment]
I'll try to tackle the issue #243 this week so we can make a 1.1.0 release with this one? #300 should be backported then. It is a bugfix anyway.

Don't you agree @mjs?

**Comment by mjs** [comment]
Just backported #300 to 1.x branch! See a5164efcb76c705703ef05058256f3df1ff084b2 & 87aae14ecabd8dbde5cba7e761769c3aaf9a8585.

**Comment by mjs** [comment]
@anaswy: Looks like we're very close to a 1.1.0 release which now has the fix.

**Comment by mlorant** [comment]
@anaswy 1.1.0, fixing this issue, has been released minutes ago!
