### ISSUE TITLE
PowerShell binary has been renamed to pwsh

### ISSUE THREAD

**Issue by pcgeek86** [mjs/imapclient#318]
The cross-platform PowerShell Core binary has been renamed from `powershell` to `pwsh`. Please consider updating references to PowerShell accordingly.

Cheers,
Trevor Sullivan
https://trevorsullivan.net

**Comment by NicolasLM** [comment]
Hey @pcgeek86, thanks for the tip.

Can you point me to the place where this change is needed? The only reference I can find is in a deleted file.

**Comment by pcgeek86** [comment]
Hey @NicolasLM, I'm sorry I can't seem to find where I had noticed a reference to it. I think it was in the docs somewhere, but I just did another search and indeed, cannot find it anymore!
