### ISSUE TITLE
Outlook IDLE not working

### ISSUE THREAD

**Issue by dsanghan** [mjs/imapclient#321]
`idle_check` is returning responses for Gmail / iCloud / etc - but does not return anything for outlook.com accounts. 

Meanwhile, imaplib seems to be working fine with the same account, returning:
```
+ idling
* 337 EXPUNGE
* 337 EXISTS
```

**Comment by dsanghan** [comment]
Seeing this on `idle()`:
```
DEBUG:imapclient.imaplib:> b'PNFD12 IDLE'
DEBUG:imapclient.imaplib:< b'+ IDLE accepted, awaiting DONE command.'
DEBUG:imapclient.imaplib:	matched r'b'\\+( (?P<data>.*))?'' => (b' IDLE accepted, awaiting DONE command.', b'IDLE accepted, awaiting DONE command.')
```
But in `idle_check`, `select.select` is returning nothing until the timeout even if mailbox events have happened.

**Comment by NicolasLM** [comment]
Hey, can you confirm that this is the version from `master`? Did you try with a very long timeout (even with `timeout=None`)?

**Comment by dsanghan** [comment]
Tried with `timeout=500` which should be long enough and yes i'm working off of `master`

**Comment by NicolasLM** [comment]
AFAIK `imaplib` does not support IDLE, can you point me to the code you tried and that worked with outlook?

**Comment by dsanghan** [comment]
I have a custom implementation written on top of imaplib - EOF's just get caught:

```
try:
    tag = self.idleConn._new_tag()
    cmd = ("%s IDLE\r\n" % (tag.decode('utf-8'))).encode('utf-8')
    self.idleConn.send(cmd)
    resp = (self.idleConn.readline().decode('utf-8')).strip()
    self.idleConn.loop = True
    if resp == '+ idling' or resp.startswith('+ IDLE accepted') or resp == '+  idling':
        while True:
            resp = (self.idleConn.readline().decode('utf-8')).strip()
            if resp.startswith('* BYE ') or len(resp) == 0:
                status.debug(self.user, 'IDLE Ended: %s' % (resp))
                break
            if resp.endswith('EXISTS'):
                status.debug(self.user, 'IDLE Triggered')
                break
            if 'FETCH' in resp and 'FLAGS' in resp:
                status.debug(self.user, 'IDLE Unread Changed')
                break
except Exception as e:
    status.debug(self.user, 'IDLE didnt end correctly: %s' % e)
finally:
    status.debug(self.user, 'IDLE Ended')
```

`status` is just a singleton wrapper on logger, so not important.

**Comment by NicolasLM** [comment]
The biggest difference is that your code leaves the socket as blocking while IMAPClient puts it in non-blocking mode.

Still `select` is pretty close to the OS, so if select does not detect something happening on the socket it probably is the truth. May I ask your platform and Python version?

**Comment by dsanghan** [comment]
Python: 3.6.2
Platform: OSX 10.13.1

Also tested this with Python 3.5.2 on Ubuntu 16.04.

Have you tried running the tests with an outlook account?

**Comment by NicolasLM** [comment]
I've tried an have the same results as you. The most interesting things is that even leaving the socket in blocking mode does not do any good:

```python
>>> s.idle()
2017-12-13 14:34:57,342 - DEBUG: > b'CIAJ4 IDLE'
2017-12-13 14:34:57,631 - DEBUG: < b'+ IDLE accepted, awaiting DONE command.'
2017-12-13 14:34:57,632 - DEBUG: 	matched r'b'\\+( (?P<data>.*))?'' => (b' IDLE accepted, awaiting DONE command.', b'IDLE accepted, awaiting DONE command.')
>>> s._sock.recv()
[blocking here]
```

**Comment by NicolasLM** [comment]
Scratch that, it works fine, I just forgot to select the inbox before...

```python
>>> s.select_folder("Inbox")
>>> s.idle()
2017-12-13 14:47:33,167 - DEBUG: > b'POOP6 IDLE'
2017-12-13 14:47:33,789 - DEBUG: < b'+ IDLE accepted, awaiting DONE command.'
2017-12-13 14:47:33,789 - DEBUG: 	matched r'b'\\+( (?P<data>.*))?'' => (b' IDLE accepted, awaiting DONE command.', b'IDLE accepted, awaiting DONE command.')
>>> s.idle_check()
2017-12-13 14:48:26,342 - DEBUG: < b'* 4 RECENT'
2017-12-13 14:48:26,342 - DEBUG: < b'* 4 EXISTS'
[(4, b'RECENT'), (4, b'EXISTS')]
>>> s.idle_done()
>>> s.logout()
```

**Comment by dsanghan** [comment]
Alright, found the issue. If you had previously selected the folder with `readOnly = True`, then select with `readOnly = False`, you don't get the responses on idling. Weird.

**Comment by dsanghan** [comment]
Thanks for the help!
