### ISSUE TITLE
Interrupt IDLE manually

### ISSUE THREAD

**Issue by dsanghan** [mjs/imapclient#322]
Is there a quick way to get out of `idle_check` with a large timeout (by somehow interrupting `select.select`)?

One way is to add another `os.pipe` in select.select's read fd's and returning it in `idle_check`. Writing to the pipe would interrupt it, but I was wondering if there was a better way to do it.

**Comment by NicolasLM** [comment]
I wouldn't use `os.pipe` but rather [`socket.socketpair`](https://docs.python.org/3/library/socket.html#socket.socketpair). You can even instruct signal handlers to automatically write in this socket.

**Comment by dsanghan** [comment]
Cool - socket.socketpair works well! Thanks!
