### ISSUE TITLE
Long running process, error = hang

### ISSUE THREAD

**Issue by robehickman** [mjs/imapclient#327]
I have an email notification system which uses imapclient in a long-running process, this system has been in use for almost two years. It can run for several weeks or several hours but inevitably randomly stops checking for mail changes.

Trying to debug this I wrote the code below which I've had running on my desktop since yesterday. It runs the imap client in a subprocess in case some internal state is causing the hang. However this still hangs, see below.

``` python
from imapclient import IMAPClient
from multiprocessing import Process, Queue
import time

account = {
    'smtp_server':   'xxx',
    'smtp_port':     '993',
    'smtp_username': 'xxx',
    'smtp_password': 'xxx' }

def f(name, q):
    try:
        server = IMAPClient(account['smtp_server'], account['smtp_port'], use_uid=True, ssl=True)
        server.login(account['smtp_username'], account['smtp_password'])
        folder_status = server.folder_status('Inbox', 'UNSEEN')
        unseen = int(folder_status['UNSEEN'])
        q.put({'unseen' : unseen})
    except:
        q.put({'unseen' : 'error'})

q = Queue()
errors = 0
while True:
    p = Process(target=f, args=('bob',q))
    p.start()
    p.join()
    res = q.get()
    if res['unseen'] == 'error':
        errors += 1
    print res
    print errors

    time.sleep(30)
```

Below is the final output from this script, it encountered an error, completed 3 mail checks following this with no errors and has hung permanently. Due to the catch-all try block, the only place I can see where this could have stopped is within the  IMAPClient(), login() or folder_status() methods.

```
0
{'unseen': 163}
0
{'unseen': 163}
0
{'unseen': 163}
0
{'unseen': 163}
0
{'unseen': 'error'}
1
{'unseen': 163}
1
{'unseen': 163}
1
{'unseen': 163}
1
-- no further output for several hours --
```

**Comment by NicolasLM** [comment]
I bet it is related to doing network calls without a timeout. The connection may be abruptly closed by the server and the client waiting indefinitely for a response that will never come.

You can setup debug logging to have a better view of what happens.

**Comment by robehickman** [comment]
I added the following code in the docs to my script but am not seeing log output.

``` python
import logging

logging.basicConfig(
    format='%(asctime)s - %(levelname)s: %(message)s',
    level=logging.DEBUG
)
```

Dosn't imapclient set timeouts on sockets?

**Comment by NicolasLM** [comment]
You have to use the code from master to have IMAPClient use Python logging module.

There is no timeout by default but you can add one with `timeout=60`. This is the same behavior as `requests`.

**Comment by robehickman** [comment]
Added a timeout, will see if that fixes it.

**Comment by robehickman** [comment]
Timeout seems to have fixed the problem in the local test. Added the timeout to the system running on a raspberry pi and getting an error regarding unknown parameter - was this added recently? Working on updating imapclient but it's being difficult.

**Comment by NicolasLM** [comment]
It was added by https://github.com/mjs/imapclient/commit/2ea3892397789fdd169225ddd1888bd263e23442. It should be available from the 1.0 release.

**Comment by robehickman** [comment]
That was around the time I write this so guess I just missed it.

**Comment by NicolasLM** [comment]
What prevents you from upgrading IMAPClient? If it's dependency issues, try installing it directly from `master`.

**Comment by robehickman** [comment]
Update was complaining setuptools needed updating and updating that required updating a bunch of other stuff which needed C dependencies installing, which took forever as the raspberry pi 1 is really slow. It's working now and hopefully won't hang again.

**Comment by robehickman** [comment]
Again, thanks for your help.

**Comment by NicolasLM** [comment]
No problem, closing as the timeout is likely fixing the issue. Feel free to reopen it if necessary.
