### ISSUE TITLE
Clarify who is responsible for checking for capability

### ISSUE THREAD

**Issue by NicolasLM** [mjs/imapclient#333]
It is not clear who is responsible for checking if a capability is supported by a server prior to using it. Currently `ID` and `SORT` are checked by IMAPClient, but `IDLE` or `UNSELECT` are not.

It could be:
1. IMAPClient, checking before each call to a non-standard command
2. Let the user call `has_capability` himself
3. No check at all, execute the command and let the server throw an error

**Comment by NicolasLM** [comment]
I'm personally in favor of 1. We could create a decorator to avoid the clutter of checking for capability in the function itself.

**Comment by mjs** [comment]
I agree that option 1 is the best approach. The server advertises capabilities so that the client doesn't have to send commands that won't work, and the user of IMAPClient shouldn't have to remember to do the checks themselves.
