### ISSUE TITLE
Certificate verify failed (ssl.SSLError)

### ISSUE THREAD

**Issue by JuliaRakitina** [mjs/imapclient#339]
According to documentation (https://imapclient.readthedocs.io/en/master/concepts.html#tls-ssl)
I am trying to connect to Microsoft Exchange server

**HOST = 'webmail.host.com'
USERNAME = 'dms-user'
PASSWORD = 'password'
ssl_context = ssl.create_default_context(cafile="/path/to/ssl_certificate.crt")
with IMAPClient(HOST, ssl_context=ssl_context) as server:
         server.login(USERNAME, PASSWORD)**

But code fails with error

> Traceback (most recent call last):
>   File "/home/dms/dsm_mail_listener.py", line 107, in <module>
>     with IMAPClient(HOST, ssl_context=ssl_context) as server:
>   File "/usr/local/lib/python2.7/site-packages/imapclient/imapclient.py", line 194, in __init__
>     self._imap = self._create_IMAP4()
>   File "/usr/local/lib/python2.7/site-packages/imapclient/imapclient.py", line 229, in _create_IMAP4
>     self._timeout)
>   File "/usr/local/lib/python2.7/site-packages/imapclient/tls.py", line 44, in __init__
>     imaplib.IMAP4.__init__(self, host, port)
>   File "/usr/local/lib/python2.7/imaplib.py", line 173, in __init__
>     self.open(host, port)
>   File "/usr/local/lib/python2.7/site-packages/imapclient/tls.py", line 50, in open
>     self.sock = wrap_socket(sock, self.ssl_context, host)
>   File "/usr/local/lib/python2.7/site-packages/imapclient/tls.py", line 32, in wrap_socket
>     return ssl_context.wrap_socket(sock, server_hostname=host)
>   File "/usr/local/lib/python2.7/ssl.py", line 363, in wrap_socket
>     _context=self)
>   File "/usr/local/lib/python2.7/ssl.py", line 611, in __init__
>     self.do_handshake()
>   File "/usr/local/lib/python2.7/ssl.py", line 840, in do_handshake
>     self._sslobj.do_handshake()
> ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)
> 

System 

> CentOS Linux release 7.3.1611 (Core)
> Python 2.7.14
> IMAPClient-2.0.0

no installed certifi library

**Comment by NicolasLM** [comment]
Hi,

IMAPClient delegates most of the SSL handling to Python so your problem is very likely in the usage of the `SSLContext` or in the cert itself.

Your example path name (`ssl_certificate.crt`) makes me think that you are giving the path of a certificate while a Certificate Authority file is expected. For more information see https://docs.python.org/2/library/ssl.html#certificates

**Comment by JuliaRakitina** [comment]
Thank you. I will check

**Comment by NicolasLM** [comment]
Also I assumed that you want to validate the server identity, but maybe what you have is a client certificate (used by a server to validate your identify). Can you confirm what is the certificate you have?

**Comment by JuliaRakitina** [comment]
Yes, this certificate is for client... Before changing Exchange server everything worked ok without ssl. Now it does not work. By the way script runs in intranet not access to Internet

**Comment by JuliaRakitina** [comment]
Yes! Everything worked like a charm :+1:

**Comment by NicolasLM** [comment]
Great, we need to add that to the documentation.
