### ISSUE TITLE
How to store company name to header of an email and search the email with company name?

### ISSUE THREAD

**Issue by quangvinh1305** [mjs/imapclient#343]
Hi developers,

I would like to store company name and search it as headers of an email.
How can i do that?

Thanks,
Vinh

**Comment by NicolasLM** [comment]
Hi,

Composing the message is up to you, but let's say your header is `X-Company-Name: foo`, you would search for messages with:

```python
c.search(["HEADER", "X-Company-Name", "foo"])
```

**Comment by NicolasLM** [comment]
Closing as the answer is provided and the question is more about IMAP in general than IMAPClient in particular.
