### ISSUE TITLE
How can i read idle EXISTS notification ?

### ISSUE THREAD

**Issue by gdomod** [mjs/imapclient#344]
Hi, 

i want to read message of idle EXISTS (new mail). but how can i fetch mail with no uid ?

('Server sent:', [(141, 'EXISTS')])

**Comment by NicolasLM** [comment]
Hi,

The same way you would if you didn't receive an IDLE notification: using `UIDVALIDITY` and `UIDNEXT`. So ideally you would have a "task" synchronizing the mailbox without IDLE and you would trigger the task when you receive an `EXISTS` while idling.

**Comment by NicolasLM** [comment]
Closing as the question is more about IMAP in general rather than IMAPClient in particular. Feel free to reopen it.
