### ISSUE TITLE
Error Appending mails in python3

### ISSUE THREAD

**Issue by imaptester1** [mjs/imapclient#348]
I am migrating a code base from python2 to python3. I am facing the below error when I try to append a mail to the folder...

command: APPEND => unexpected response: b"b'Received: BAD Command Error. 10"

I tried everything, but not able to figure out the error's RC. Below is the code:

self.digest_folder.append(self.digest_folder_name, mail)

where, digest folder is the folder to which I am trying to append.

**Comment by NicolasLM** [comment]
Hey, can you provide your full code interacting with IMAPClient and [debug logs](http://imapclient.readthedocs.io/en/master/concepts.html#logging)?

**Comment by imaptester1** [comment]
Sorry for the wrong ticket. When I was trying to reproduce the error, I identified the issue is because of the encoding issue at the message reading side. The server is sending the messages in non utf-8 format. I had to decode the message to get it to working.

Closing the ticket.
