### ISSUE TITLE
Interactive session does not use TLS by default.

### ISSUE THREAD

**Issue by duesee** [mjs/imapclient#353]
The interactive session `python -m imapclient.interact -H <host> -u <user> ...` does not use TLS by default.

I also wonder if it is possible to reliably only allow encrypted connections, i.e. only port 993 via TLS. I would especially like to turn off STARTSSL as it may allow downgrade attacks. Is `STARTSSL=False` and `SSL=True` sufficient or may the IMAPClient fallback to a plaintext connection in some cases?

**Comment by NicolasLM** [comment]
Right, we moved to ssl by default on the programing interface `imapclient.IMAPClient` but forgot the interactive part. Would you like to make a PR about it?

If it comes to `STARTTLS`, leaving it to its default value should be enough to make sure it is not used.

**Comment by duesee** [comment]
Yes :-) See #354 I looked through the code and it seems that changing the --ssl value to true is sufficient. The ports are set to 143 and 993 according to the use_ssl value, right?

**Comment by duesee** [comment]
Oops, no wait. It is a flag and there is no according flag to disallow ssl. What do you think about --insecure?

**Comment by NicolasLM** [comment]
Good catch, I prefer `--insecure` or `--no-ssl`.

**Comment by duesee** [comment]
Okay, can you have a look? I found it a bit tricky to keep the ssl option and to introduce --insecure. I don't know exactly how OptionParser works, so there could be room for improvement.

**Comment by NicolasLM** [comment]
Perfect, thank you!
