### ISSUE TITLE
Decode mime header

### ISSUE THREAD

**Issue by lfkpoa** [mjs/imapclient#358]
When I get the subject field from the Envelope it is still mime encoded.
It would be nice if it could be already decoded or if there was a method in the package to decode it.
Searching the internet I found the following method to decode it, using email package:
```
def decode_mime_words(s):
    return u''.join(
        word.decode(encoding or 'utf8') if isinstance(word, bytes) else word
		for word, encoding in email.header.decode_header(s))
```
https://code.i-harness.com/en/q/c4e5d5

**Comment by mjs** [comment]
I agree this would be nice to have. This is also mentioned in https://github.com/mjs/imapclient/issues/149. I've scheduled this for the 3.1.0 release.
