### ISSUE TITLE
AttributeError: 'SearchIds' object has no attribute '_store' on return from set_flags or add_flags

### ISSUE THREAD

**Issue by doboseal** [mjs/imapclient#364]
Getting this message:

File "/usr/local/lib/python3.7/site-packages/imapclient/imapclient.py", line 1103, in set_flags
    return self._store(b'FLAGS', messages, flags, b'FLAGS', silent=silent)
AttributeError: 'SearchIds' object has no attribute '_store'

Running the code below (extraneous bits removed) in Eclipse with PyDev, MacOS Mojave, Python 3.7, imapclient 2.1.0

I get the same message (but for the method name) whether I use "set_flags" or "add_flags". Messages are being flagged as SEEN, it's only when imapclient tries to return from flagging that the error is thrown.

`	
        

	import email
	from imapclient import IMAPClient

	class Alarm:
	    '''
	    Uses email to maintain alarm status
	    '''
	    host = 'mymailhost.com'
	    user = 'me@mymailhost.com'
	    pwd = 'mypass'

	    def __init__(self):
	        '''
	        Constructor
	        '''
		self.armed = False
		self.mode = None

	    def away(self):
	        '''
	        Reads emails from security system to determine latest status
	        '''
	        with IMAPClient(Alarm.host, use_uid=True, ssl=True) as server:
	            server.login(Alarm.user, Alarm.pwd)
	            server.select_folder('INBOX', readonly=False)
	            messages = server.search('UNSEEN')
	            for uid, message_data in server.fetch(messages, 'RFC822').items():
	                email_message = email.message_from_bytes(message_data[b'RFC822'])
	                payload = email_message.get_payload()
			# redacted parsing the payload to get latest armed status and mode
	            if len(messages) > 0: 
	                 IMAPClient.set_flags(messages,'SEEN',True)
	        if self.armed and self.mode == 'away':
	            return True
	        else:
	            return False
`

**Comment by doboseal** [comment]
Hmm. Just tried this by calling the method on the instance, rather than the class, and got no error message. I guess that's my bad--not sure why it needs to be an instance call, but then I'm a Python noob! Nevermind!

**Comment by NicolasLM** [comment]
To set flags you need a connection to the server and only the instance has this connection (which is created when instantiating the class).  
It's not very common in Python to call methods directly on classes.

**Comment by doboseal** [comment]
Makes perfect sense, thanks for the explanation!On Dec 10, 2018 2:00 PM, Nicolas Le Manchet <notifications@github.com> wrote:To set flags you need a connection to the server and only the instance has this connection (which is created when instantiating the class).
It's not very common in Python to call methods directly on classes.
