### ISSUE TITLE
copy() always returns None 

### ISSUE THREAD

**Issue by secretofthesteel** [mjs/imapclient#365]
Hi,
My IMAP server (newest dovecot 2.3) doesn't support MOVE capability so I have to use two functions to move email into another folder: first copy() and finally delete_messages(). I would like to be absolutely sure that email is successfully copied before I delete them from original folder. In the docs I read that copy() function returns operation codes from IMAP server:

>  Returns the COPY response string returned by the server.

but for me it always returns None (even if I provide non existing UID). It scares me a little. How to get a return code of successful copy before email removal?

**Comment by mjs** [comment]
Can you try enabling logging to see what the server is actually returning from the COPY. If there's something being returned we should be able to have IMAPClient return it.

More on enabling logging here: https://imapclient.readthedocs.io/en/2.1.0/concepts.html#logging
