### ISSUE TITLE
Check new emails Continuously 

### ISSUE THREAD

**Issue by himanshusagar** [mjs/imapclient#366]
Hi,
Is it possible to run a thread and check emails continuously and see if there's a new one ? 
A naive way would be to run following inside while loop: 
0. IMAPClient.login()
1. Process unread emails
2. Mark processed emails as read.
3. IMAPClient.logout()
4. sleep(5)
5. Repeat

I am looking for something like login once and resynchronize with server for new unread emails?
EDIT: I have tried IDLE mode using [this](https://github.com/mjs/imapclient/blob/master/examples/idle_example.py) and pulled UIDNEXT value of inbox folder. However, supplying same uid value(UIDNEXT) in server.fetch(), causes no results. I feel like i am missing some server.resynchronize_with_imap_server() command. Any thoughts?

**Comment by MaPoLom** [comment]
Did you find a solution to this problem. I'm looking for the same thing.
It seems simple in NodJs  [https://github.com/jcreigno/nodejs-mail-notifier](url) but there is no complete solution to be found on the net for python

**Comment by himanshusagar** [comment]
Hi MaPoLom,

Hope your're doing well. 
As it turns out, it is not possible to be notified for new emails in python. Your only option is to check for new/unread emails via some library( [easyimap](https://github.com/keitaoouchi/easyimap) ) every 5/10 mins.

**Comment by NicolasLM** [comment]
It is definitely possible to do it with IMAPClient. A robust solution requires to use IMAP IDLE for notification and fallback to polling for mailboxes not supporting IDLE.

I used to listen for changes on thousands of mailboxes with a code similar to this one: https://github.com/mjs/imapclient/pull/324/files
