### ISSUE TITLE
Can't make `set_flags` work

### ISSUE THREAD

**Issue by soywod** [mjs/imapclient#369]
Hi,
I try to change message flag using `set_flags`, but nothing happens. I get no error, just an empty dict (and the flag is not set). I don't get what I'm doing wrong, any idea?

```python3
_imap = IMAPClient(host=_host, port=993)

emails = []
criteria = ['NOT', 'DELETED']
if (seq > 29): criteria.append('%d:%d' % (seq, seq - 29))

search = _imap.search(criteria)
fetch = _imap.fetch(search, ['ENVELOPE', 'INTERNALDATE', 'BODY[]', 'FLAGS'])

# I use this uid to set flags later
for [uid, data] in fetch.items():
  ...
```

I tried many different things, none worked:
```python3
_imap.set_flags([uid], [r'\Seen'])
_imap.set_flags(uid, r'\Seen')
_imap.set_flags(uid, 'SEEN')
_imap.set_flags(uid, b'\\Seen')
...
```

Thank you for your help!

**Comment by NicolasLM** [comment]
Hi,
Can you try `_imap.set_flags([uid], [imapclient.SEEN])`?

**Comment by soywod** [comment]
Still nothing `INFO:root:{}`

**Comment by NicolasLM** [comment]
Can you show debug logs so we can see what goes in/out the server? https://imapclient.readthedocs.io/en/2.1.0/concepts.html#logging

**Comment by soywod** [comment]
Ah got it...
```txt
2019-01-11 12:45:42,743 - DEBUG: 	matched b'(?P<tag>EHDG\\d+) (?P<type>[A-Z]+) (?P<data>.*)' => (b'EHDG8', b'OK', b'Store ignored with read-only mailbox (0.001 + 0.000 secs).')
```

Stupid me, it's because of:
```python3
_imap.select_folder(folder, readonly=True)
```

Thank you for your help!

**Comment by NicolasLM** [comment]
Great, I'm glad you got it to work.
