### ISSUE TITLE
Attachment support?

### ISSUE THREAD

**Issue by S0larflare** [mjs/imapclient#370]
Apologies if this has been mentioned elsewhere, but I couldn't see anything that related to it. Does the client support emails with attachments? Specifically I am interested in emails with an email attached so that I can parse them for their body, headers and subject - is this possible with imapclient?

**Comment by NicolasLM** [comment]
I'm not sure it's possible to get meaningful data from an email attached to an email with IMAP directly. However you can download the full email and parse attachments using Python: https://imapclient.readthedocs.io/en/2.1.0/concepts.html#working-with-fetched-messages

**Comment by S0larflare** [comment]
OK no problem, I just wondered if it was something out of the box that I had missed. Thanks for your quick response! :smile:
