### ISSUE TITLE
Check if connection is closed (TimeoutError)

### ISSUE THREAD

**Issue by snake-soft** [mjs/imapclient#386]
First big thanks to all contributors of this great lib!

I'm searching for a Method to test if a long existing imap connection ran into the
> *** TimeoutError: [Errno 110] Connection timed out

If the server timed out, every imap command takes minutes to respond the error above.
After this waiting period followed by the TimeoutError mess
I couldn't find any way although i searched multiple days.

I know, normally i should close the imap connection but for design purposes i want to leave it open as long as possible and reinit if closed by server.

**Comment by mjs** [comment]
Are you setting a timeout for the connection when you instantiate the IMAPClient instance?

See the `timeout` argument here: https://imapclient.readthedocs.io/en/2.1.0/api.html#imapclient.IMAPClient
