### ISSUE TITLE
 FETCH command error: BAD ['Command Error. 10']

### ISSUE THREAD

**Issue by steven-cuthill-otm** [mjs/imapclient#387]
Hello, 

Have this block of code, but getting an error that not super helpful, 

`imaplib.error: FETCH command error: BAD ['Command Error. 10']
`

basically i want to search for all unread emails that are send from a particular domain ( not figured out that search pattern yet )  once i have fetched the data i want to mark them as read so they are not processed again. but its sadly having issues. any help would be awesome. 

```    messages = server.search('UNSEEN')

    for uid, message_data in server.fetch(messages, 'RFC822').items():
        server.add_flags([uid], 'SEEN', silent=False)
        email_message = email.message_from_string(message_data[b'RFC822'])```

**Comment by mjs** [comment]
Hi,

Which line is that error coming from? 

One possible problem that I can see is that the flags in the add_flags call are supposed to be passed as a sequence, so perhaps try: `server.add_flags([uid], ['SEEN'], silent=False)`

**Comment by mjs** [comment]
Closing due to lack of information. Feel free to reopen.
