### ISSUE TITLE
IMAP IDLE: return the UID message

### ISSUE THREAD

**Issue by ggreco77** [mjs/imapclient#389]
Using the default example [here](https://imapclient.readthedocs.io/en/2.1.0/advanced.html#watching-a-mailbox-using-idle), the `.idle_check` returns just a list of received IDLE responses: `Server sent: [(6, b'EXISTS')]`. However I need the message UID to fetch the e-mail - `Server sent: [(4, b'FETCH', (b'UID', 31, b'FLAGS', ()))]` Can I receive the UID message in the IMAP IDLE response?

Best,
Giuseppe

**Comment by mjs** [comment]
I'm not aware of any way to get an IMAP server to provide UIDs in IDLE responses. This isn't part of the protocol.

Your best bet is probably to just use IDLE responses to know that *something* has changed in the mailbox and then do a search to figure out *what*. You can optimise the search by caching the last seen UID for the mailbox andt, if the server supports [RFC7162](https://tools.ietf.org/html/rfc7162), using MODSEQ with SEARCH to find any flag changes.
