### ISSUE TITLE
Fetching without change 'seen' flag

### ISSUE THREAD

**Issue by rptl** [mjs/imapclient#404]
Why below code is marking msgs as seen? I want to mark them manually later, not during fetch.

`response = client.fetch(msgids, ['FLAGS', 'ENVELOPE', 'BODY[TEXT]'])`

**Comment by rptl** [comment]
Just realized that BODY[TEXT] mark messages as SEEN by design.  BODY.PEEK worked like a charm.

**Comment by mjs** [comment]
Glad you figured it out
