### ISSUE TITLE
ImportError: cannot import name 'IMAPClient' from 'imapclient' 

### ISSUE THREAD

**Issue by alamaxjashek** [mjs/imapclient#409]
When I try run the python script I have this error:
`
ImportError: cannot import name 'IMAPClient' from 'imapclient'
`
My script:

```
from imapclient import IMAPClient
import email

host = 'imap.server.com'
user = 'mail@domain.tld'
password = 'myPasword'
ssl = True

server = IMAPClient(host, use_uid=True, ssl=ssl)
server.login(user, password)

```

**Comment by its5Q** [comment]
Make sure you are running the correct version of Python where you have installed the library. It may be possible that you have 2 versions of Python on your system.

**Comment by mjs** [comment]
It might help to see where IMAPClient is being imported from. To check this, try adding this at the top of your program:

```python
import imapclient
print(imapclient.__file__)
```

I'm going to close this for now as it looks like an issue specific to your environment. Feel free to reopen if you believe there's something we need to fix with IMAPClient itself.
