### ISSUE TITLE
Example of fetching without changing 'seen' flag?

### ISSUE THREAD

**Issue by geerlingguy** [mjs/imapclient#414]
Over in #40, @rptl asked how to check a message without marking it as `seen`... and I have the same question.

In his answer, he mentioned `BODY.PEEK` could be used to get the contents without marking as read, but in my own testing I can't find any permutation that works that way. No matter what, the message is always marked 'seen'.

Here's the code I'm _trying_ to use:

```python
server.fetch(messages, ['BODY.PEEK[HEADER.FIELDS (From Subject)]'])
```

(I'd like to just get the `From` and `Subject`.)

**Comment by NicolasLM** [comment]
Hi, it should work. Did you try with another server just to confirm the behavior?

I guess you could also try to open the mailbox in "read-only" with [EXAMINE](https://tools.ietf.org/html/rfc3501#section-6.3.2).

**Comment by geerlingguy** [comment]
This was with Office365... and I know that system does all kinds of strange things :/ — haven't tested with another provider though.
