### ISSUE TITLE
Accessing the socket used by `IMAPClient`

### ISSUE THREAD

**Issue by BoniLindsley** [mjs/imapclient#450]
To watch a mailbox using IDLE, the current documentation suggests [using a busyloop](https://imapclient.readthedocs.io/en/2.2.0/advanced.html#watching-a-mailbox-using-idle) with a relatively small timeout to check for responses. A small timeout because `IMAPClient.idle_check` uses a [blocking poll](https://github.com/mjs/imapclient/blob/master/imapclient/imapclient.py#L936) with this timeout and handling `KeyboardInterrup` is not possible while it blocks. An alternative to the busy loop was suggested in <https://github.com/mjs/imapclient/issues/322>, using `select.select` to poll both the connecting socket and a separate socket.

However, in order to poll the socket, access to the underlying socket is required, available as `IMAPClient._sock`. My understanding is that this attribute is an implementation detail. Can this be relied upon? If not, is it possible to make the socket available as part of the API?

**Comment by mjs** [comment]
I'd be open to exposing the underlying socket via a socket() method, along with "here be dragons" style documentation :)

Recent versions of imaplib in the standard library already have a socket() method.
