### ISSUE TITLE
Status of continuous integration

### ISSUE THREAD

**Issue by BoniLindsley** [mjs/imapclient#455]
The current project README [links](https://github.com/mjs/imapclient/blob/0279592557495d4ddf7619b17ed9e73b21161bdf/README.rst#test-status) to, what appears to be, an obsolete Travis-CI page: <https://travis-ci.org/mjs/imapclient/branches>. It probably should be updated.

Should it be replaced by something else? Is there a CI set up?

**Comment by NicolasLM** [comment]
Yes, I guess we should move to Github Actions.
