### ISSUE TITLE
ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context

### ISSUE THREAD

**Issue by alkim0** [mjs/imapclient#466]
With Python 3.10 and imapclient 2.2.0, I get the following error when I try to use it:
```
ssl.SSLError: Cannot create a client socket with a PROTOCOL_TLS_SERVER context
```
It turned out that I let IMAPClient create the default ssl context, and I see that: https://github.com/mjs/imapclient/blob/d26975843b89ad4dcd004803a3b7909530c5bd6a/imapclient/tls.py#L30
According to the ssl module docs, `Purpose.CLIENT_AUTH` is

> Option for create_default_context() and SSLContext.load_default_certs(). This value indicates that the context may be used to authenticate web clients (therefore, it will be used to create server-side sockets).

Given that imapclient is mostly used to access imap servers, I think this should be changed to:
```
ssl_context = ssl.create_default_context(purpose=ssl.Purpose.SERVER_AUTH)
```
`Purpose.SERVER_AUTH` has the following documentation:
> Option for create_default_context() and SSLContext.load_default_certs(). This value indicates that the context may be used to authenticate web servers (therefore, it will be used to create client-side sockets).

As a side note, passing in a custom `ssl_context` with the `SERVER_AUTH` purpose works just fine, but I still think the default should be changed.

**Comment by mjs** [comment]
You're absolutely correct - this needs to be fixed.

**Comment by mjs** [comment]
Damn, I just released 2.3.0 with this bug still there. I'll sort it out and do another release.

**Comment by thesamesam** [comment]
> Damn, I just released 2.3.0 with this bug still there. I'll sort it out and do another release.

Thank you!

**Comment by thesamesam** [comment]
Would you mind pushing the git tag too?

**Comment by mjs** [comment]
Sorry, done!
