### ISSUE TITLE
"client.search(['UID', f'99:*'])" does not return the very last message

### ISSUE THREAD

**Issue by sphh** [mjs/imapclient#473]
As suggested in #471, my code uses `IDLE` to watch for changes and whenever a change is detected, my program tries to figure out, what has changed. In my case I am interested in the newly arrived messages. I keep track of the highest UID I've dealt with previously in the variable `uid_seen`.

I then get the UIDs of the new messages with a search:
```python3
new_uids = client.search(['UID', f'{uid_seen}:*', 'UNDELETED', 'UNSEEN')
```

Unfortunately the list `new_uids` contains the UIDs of all new messages, _but not the UID of the last message_.

I also tried to use the following search
```python3
new_uids = client.search(['UID', f'{uid_seen}:*')
```
with the same result: _The UID of the very last message is missing_.

Is this a bug of `imaplib`, the IMAP server or of my search? How could I get the UID of the very last message included in my list of `new_uids`?

I use the latest `imapclient` installed with `apt install imapclient` and `dovecot` (`1:2.3.4.1-5+deb10u6`) on a Debian system.

**Comment by mjs** [comment]
Closing this as there's also a discussion thread at https://github.com/mjs/imapclient/discussions/472
