### ISSUE TITLE
Drop support for Python 3.4

### ISSUE THREAD

**Issue by JohnVillalovos** [mjs/imapclient#479]
Python 3.4 is no longer supported upstream as of 18-Mar-2019 [1]. I propose that support for Python 3.4 be removed.

This would primarily consist of:
  * Possibly do a release first
  * Update documentation
  * Remove testing of Python 3.4
  * In `setup.py` do `python_requires=">=3.5.0"`
  * Update the versions in the description on PyPI

[1] https://endoflife.date/python

**Comment by NicolasLM** [comment]
That seems reasonable to me.

**Comment by mjs** [comment]
Sorry for the slow response. My family and I have all been hit badly with COVID.

I support this change. In fact, I think we could drop 3.5 too. Even a slow moving distro like RHEL8 has Python 3.6 and an old Ubuntu LTS release like 18.04 has 3.6 as well. Thoughts?

As far as releases go, the following needs to happen:
- a 2.3.0 release needs to happen which is cut from just before the Python 2 removal changes were made. This will be the last release that supports Python 2. I will get that done this week.
- a 3.0.0 release then needs to happen from what is currently master (92255e96cd555cbf105e6a007c473aeb1ad2d343)
- then a 3.1.0 release which removes support for Python 3.4 / 3.5.

The changes for removing support for Python 3.4 and 3.5 can land whenever. We can always tag an earlier revision for the 3.0.0 release.

**Comment by JohnVillalovos** [comment]
> Sorry for the slow response. My family and I have all been hit badly with COVID.

Oh sorry to hear that, I hope you all recover quickly!

> I support this change. In fact, I think we could drop 3.5 too. Even a slow moving distro like RHEL8 has Python 3.6 and an old Ubuntu LTS release like 18.04 has 3.6 as well. Thoughts?

I would support dropping Python 3.5. I would also support dropping Python 3.6 support as it is also end-of-life. https://endoflife.date/python

I am one of the maintainers of the python-gitlab project and we have already dropped support for Python 3.6. With the `python_requires` value in `setup.py` it works pretty well. Older versions of Python will get the last release that is listed to work for their version. So they are able to still keep working.  As a note RHEL 8 does have a `python39` package available which is Python 3.9. And Ubuntu 18.04 has a `python3.8` package available.

> As far as releases go, the following needs to happen:
> 
>     * a 2.3.0 release needs to happen which is cut from just before the Python 2 removal changes were made. This will be the last release that supports Python 2. I will get that done this week.

👍

> 
>     * a 3.0.0 release then needs to happen from what is currently master ([92255e9](https://github.com/mjs/imapclient/commit/92255e96cd555cbf105e6a007c473aeb1ad2d343))
👍

>     * then a 3.1.0 release which removes support for Python 3.4 / 3.5.
> 
> 
> The changes for removing support for Python 3.4 and 3.5 can land whenever. We can always tag an earlier revision for the 3.0.0 release.

Sounds good to me. Thanks!

One of the reasons I was pushing for this is that I would like to add some type-hints, if amenable. And getting to at least Python 3.6 would be great.

**Comment by mjs** [comment]
For now, let's just get to a minimum of Python 3.6. That feels safe to me.

**Comment by mjs** [comment]
I've just released 2.3.0, see https://github.com/mjs/imapclient/discussions/481

**Comment by mjs** [comment]
@JohnVillalovos Were you planning on submitting a PR to remove support for Python 3.4 and 3.5?

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos Were you planning on submitting a PR to remove support for Python 3.4 and 3.5? 

Sure I can do that. I can get it done this weekend. But I won't be offended if you want to do it 😊

**Comment by JohnVillalovos** [comment]
> @JohnVillalovos Were you planning on submitting a PR to remove support for Python 3.4 and 3.5?

Submitted #483
