### ISSUE TITLE
https://imapclient.readthedocs.io/ goes to old docs

### ISSUE THREAD

**Issue by JohnVillalovos** [mjs/imapclient#485]
When I go to: https://imapclient.readthedocs.io/

It then redirects to: https://imapclient.readthedocs.io/en/2.2.0/

Which then says that the latest version of the docs is at: https://imapclient.readthedocs.io/en/2.3.1/

**Comment by mjs** [comment]
Thanks for reporting this. I've fixed it now to always load `master` which is likely to be closer to the current release than anything else.
