### ISSUE TITLE
expunge func assumes UIDPLUS capability and uses UID EXPUNGE in error

### ISSUE THREAD

**Issue by TinyBigJacko** [mjs/imapclient#496]
Hi guys,
Firstly, thanks for a fine piece of code that's extremely vital to the community. You are to be commended and I'm incredibly grateful.

However, I think I have detected a small error that has some ramifications which break certain mass-move/delete operations on IMAP4 servers that do not yet support UIDPLUS (https://github.com/hmailserver/hmailserver being one such)

It appears that the imapclient.expunge function here: https://github.com/mjs/imapclient/blob/d0f5c4e927ddda1972066ef04242a09d2dc2a666/imapclient/imapclient.py#L1469
...assumes that if it is given a list of UIDs by a caller, then it is safe to just go ahead and use UID EXPUNGE command-methodology to work through the list and expunge them, without actually confirming that UIDPLUS (and thereby UID EXPUNGE) is even available on the current IMAP server.

This is potentially unsafe, though thankfully not destructive, but it will derail operations that are working through a mailbox folder, expecting batches of messages to have been moved/deleted, such as DMARC report processing. See [parsedmarc](https://domainaware.github.io/parsedmarc/) as an example which relies, ultimately, on IMAPClient, and (imho acceptably) assumes that a UID list given to an interim mail-handler ([Mailsuite](https://seanthegeek.github.io/mailsuite/) will be taken care of, in terms of dealing with any UIDPLUS capability or not). Mailsuite evidently makes the same assumption, and defers the problem to IMAPClient, which makes sense, really, as IMAPClient is 'nearer the metal'.

As an aside, the RFCs referred to in IMAPClient's expunge function have been obsoleted::
https://www.rfc-editor.org/rfc/rfc9051#section-6.4.3 now defines the EXPUNGE command (old style global expunge) in the current IMAP RFC
https://www.rfc-editor.org/rfc/rfc9051#section-7.5.1 describes responses from IMAP servers when using EXPUNGE

Not a lot has changed (in terms of EXPUNGE), but you might like to point to the newer RFC anyway.

https://www.rfc-editor.org/rfc/rfc4315#section-2.1 describes the newer UID EXPUNGE command, which is part of UIDPLUS and not a de facto capability of all IMAP servers yet, sadly. Most usefully, however, it gives an alternative for handling lists of message UIDs, in the event that UID EXPUNGE isn't available:

```
      If the server does not support the UIDPLUS capability, the client
      should fall back to using the STORE command to temporarily remove
      the \Deleted flag from messages it does not want to remove, then
      issuing the EXPUNGE command.  Finally, the client should use the
      STORE command to restore the \Deleted flag on the messages in
      which it was temporarily removed.
```

**Would it be possible to beg that IMAPClient is updated to fall back to that method in the event that UIDPLUS capability is not found on the current IMAP server, please?** 

Older non-UIDPLUS-capable IMAP servers like hmailserver will misidentify the use of a UID EXPUNGE command as a broken invocation of the UID command, and report a bad or missing uid number, and not expunge anything at all. It parses the word 'UID', expects a number, then parses 'EXPUNGE' and assumes failure, and dismisses the range of UIDs that follows. 

Net result is that the messages concerned are not purged from the mailbox folder, and will remain there being detected by batching operations that are trying to process the whole folder in chunks, saving processed-output in stages - for example, a pile of DMARC reports. These tools will end up iterating the same set of emails over and over again until something else on the IMAP server randomly happens to call a global EXPUNGE (old RFC9051 method), at which point, they'll vanish and the DMARC analysis process will continue - but only for the next batch, then it's back to looping again!

If you are able to fix this, it would be greatly appreciated by a number of users, I'm sure (and definitely by me!) Processing of DMARC reports for smaller business and homeworkers who use their own open-source mailservers on Windows may be a small subset of global users, but frankly anything that makes life easier for the detection and prevention of spam and spoofed emails, has to be a good thing for the community at large, no?

Of course it's to be hoped that hmailserver eventually gains UIDPLUS functionality, but at the current time, it's not evident, and in any case, there may be other IMAP servers out there in the wild that don't. Supporting of UIDPLUS is still optional; whereas the dependence upon it without checking its availability is technically 'broken behaviour'. So hopefully IMAPClient can smooth the way with a fix?

Thanks for reading! If you need any help testing, please get in touch and I'll try and assist.
Best regards
TBJ

**Comment by axoroll7** [comment]
@TinyBigJacko 

Hello, I submitted a pull request about this issue. What do you think ?

**Comment by axoroll7** [comment]
A new pull request, which creates a function ``uid_expunge``.

**Comment by TinyBigJacko** [comment]
> @TinyBigJacko
> 
> Hello, I submitted a pull request about this issue. What do you think ?

Fantastic work, @axoroll7 - thanks. Sorry I missed this at the time (pressures of life), but I'm really happy to see this got merged-in and is now part of the main codebase. Many thanks for addressing the fix and getting it in! 👍
